default:
    @just --list

format:
    uv run ruff format
    uv run ruff check --fix

lint:
    -uv run ruff check
    -uv run ty check

ingest +ARGS:
    uv run cli ingest {{ARGS}}

chat:
    uv run cli chat
