[project]
name = "graphrag-travel-group-chat"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.2.1",
    "langchain-core>=1.0.0,<2.0.0",
    "langchain-community>=0.4.0,<1.0.0",
    "langchain-ollama>=1.0.0,<2.0.0",
    "langchain-surrealdb",
    "nanoid>=2.0.0",
]

[project.scripts]
cli = "graphrag_travel_group_chat.main:cli"

[tool.uv.sources]
langchain-surrealdb = { path = "../../", editable = true }

[dependency-groups]
dev = ["ruff>=0.12.4", "ty>=0.0.1a15"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
