default:
    @just --list

tape:
    vhs demo.tape

tape-graph:
    vhs demo-graph.tape

docker-build:
    docker build -t demo-langchain -f Dockerfile .

docker-run:
    docker run -ti --rm --name demo-langchain demo-langchain

run:
    poetry run python main.py

run-graph:
    poetry run python graph.py
