default:
    @just --list

format:
    uv run ruff format
    uv run ruff check --fix

lint:
    -uv run ruff check
    -uv run basedpyright

tape:
    vhs demo.tape

tape-graph:
    vhs demo-graph.tape

docker-build:
    docker build -t demo-langchain -f Dockerfile .

docker-run:
    docker run -ti --rm --name demo-langchain demo-langchain

run:
    uv run python main.py

run-graph:
    uv run python graph.py
